---
# Location where configuration files will be stored.
config_dir: "{{ '~' | expanduser }}"

# Domain names configuration (related services need to be enabled).
domain:
  enable: false
  name: "home.local"
  pihole: "pihole" # to access pihole via: http://pihole.home.local

# Zigbee2mqtt configuration.
zigbee2mqtt_enable: true

# Mosquitto configuration.
mosquitto:
  enable: true
  user: "pi"
  password: "{{ vault_mosquitto_password }}"

# Pi-hole configuration.
pihole:
  enable: false
  hostname: pihole
  password: "{{ vault_pihole_password }}"

# Auto Heal configuration.
autoheal:
  enable: true

# Portainer configuration.
portainer_enable: false

# Tesla custom integration configuration.
tesla_enable: false

# WebRTC custom integration configuration.
webrtc_enable: false

# Home Assistant
sidebar:
  zigbee2mqtt: true
  portainer: false
  pihole: false
  automations: true
  integrations: true

install_blueprints: true

# Global config
container_timezone: Europe/Amsterdam