---
- name: Create home-assistant and config folders on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/home-assistant{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ""
    - "/config"
  become: false

- name: Copy home-assistant docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/home-assistant-docker-compose.yml.j2
    dest: "{{ config_dir }}/home-assistant/docker-compose.yml"
    mode: 0640
  become: false

- name: Ensure home-assistant is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/home-assistant/"
    build: false
  become: false