---
- name: Create home-assistant folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/home-assistant"
    state: directory
    mode: 0755
  become: false

- name: Create home-assistant/config folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/home-assistant/config"
    state: directory
    mode: 0755
  become: false

- name: Copy home-assistant docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/home-assistant-docker-compose.yml.j2
    dest: "{{ config_dir }}/home-assistant/docker-compose.yml"
    mode: 0640
  become: false

- name: Ensure home-assistant is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/home-assistant/"
    build: false
  become: false

- name: Copy file to a temporary location
  ansible.builtin.copy:
    src: /{{ config_dir }}/home-assistant/config/configuration.yaml
    dest: /tmp/file.tmp
    mode: 0644

- name: Add lines to the temporary file
  ansible.builtin.lineinfile:
    path: /tmp/file.tmp
    line: "{{ item }}"
    state: present
    regexp: "^panel_iframe:$"
    create: yes
  with_items:
    - "panel_iframe:"
    - "  zigbee2mqtt:"
    - "    title: \"zigbee2mqtt\""
    - "    url: \"http://172.80.0.35:8080\""
    - "    icon: mdi:zigbee"
    - "    require_admin: true"

- name: Replace original file with modified file
  ansible.builtin.shell: mv /tmp/file.tmp /{{ config_dir }}/home-assistant/config/configuration.yaml
