---
- name: Create home-assistant folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/home-assistant"
    state: directory
    mode: 0755
  become: false

- name: Create home-assistant/config folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/home-assistant/config"
    state: directory
    mode: 0755
  become: false

- name: Copy home-assistant docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/home-assistant-docker-compose.yml.j2
    dest: "{{ config_dir }}/home-assistant/docker-compose.yml"
    mode: 0640
  become: false

- name: Ensure home-assistant is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/home-assistant/"
    build: false
  become: false

- name: Wait for Home Assistant configuration file
  ansible.builtin.wait_for:
    path: "{{ config_dir }}/home-assistant/config/configuration.yaml"
    state: present
    timeout: 40
    msg: Timeout to find file '{{ config_dir }}/home-assistant/config/configuration.yaml'

- name: Check if sidebar is present in Home Assistant configuration
  ansible.builtin.lineinfile:
    path: "{{ config_dir }}/home-assistant/config/configuration.yaml"
    line: "panel_iframe:"
    state: present
  register: no_sidebar_present
  check_mode: true
  
- name: Create a backup of Home Assistant configuration
  ansible.builtin.copy:
    src: "{{ config_dir }}/home-assistant/config/configuration.yaml"
    dest: /tmp/file.tmp
    mode: 0644

- name: Add panel to Home Assistant configuration
  lineinfile:
    path: /tmp/file.tmp
    line: |
      panel_iframe:
  when: no_sidebar_present.changed

- name: Check if zigbee2mqtt sidebar is present in Home Assistant configuration
  ansible.builtin.lineinfile:
    path: "{{ config_dir }}/home-assistant/config/configuration.yaml"
    line: "zigbee2mqtt:"
    state: present
  register: zigbee2mqtt_panel_present
  check_mode: true
  when: zigbee2mqtt_enable

- name: Add zigbee2mqtt sidebar to Home Assistant configuration
  ansible.builtin.blockinfile:
    path: /tmp/file.tmp
    insertafter: 'panel_iframe:'
    block: |2
        zigbee2mqtt:
          title: "zigbee2mqtt"
          url: "http://{{ ansible_default_ipv4.address }}:8080"
          icon: mdi:zigbee
          require_admin: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK zigbee2mqtt"
  register: update_config
  when: zigbee2mqtt_panel_present.changed and zigbee2mqtt_enable

- name: Check if portainer sidebar is present in Home Assistant configuration
  ansible.builtin.lineinfile:
    path: "{{ config_dir }}/home-assistant/config/configuration.yaml"
    line: "portainer:"
    state: present
  register: portainer_panel_present
  check_mode: true
  when: portainer_enable

- name: Add portainer sidebar to Home Assistant configuration
  ansible.builtin.blockinfile:
    path: /tmp/file.tmp
    insertafter: 'panel_iframe:'
    block: |2
        portainer:
          title: "portainer"
          url: "http://{{ ansible_default_ipv4.address }}:9000"
          icon: mdi:docker
          require_admin: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK portainer"
  register: update_config
  when: portainer_panel_present.changed and portainer_enable

- name: Update Home Assistant configuration
  ansible.builtin.copy:
    src: /tmp/file.tmp
    dest: "{{ config_dir }}/home-assistant/config/configuration.yaml"
    mode: 0644
  when: update_config.changed

- name: Stop home-assistant container. (Reloading config)
  community.docker.docker_container:
    name: homeassistant
    state: stopped
  when: update_config.changed

- name: Start home-assistant container. (Reloading config)
  community.docker.docker_container:
    name: homeassistant
    state: started
  when: update_config.changed

- name: Remove temp file
  ansible.builtin.file:
    path: /tmp/file.tmp
    state: absent
  when: update_config.changed == false
