---
- name: Create home-assistant folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/home-assistant"
    state: directory
    mode: 0755
  become: false

- name: Create home-assistant/config folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/home-assistant/config"
    state: directory
    mode: 0755
  become: false

- name: Copy home-assistant docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/home-assistant-docker-compose.yml.j2
    dest: "{{ config_dir }}/home-assistant/docker-compose.yml"
    mode: 0640
  become: false

- name: Ensure home-assistant is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/home-assistant/"
    build: false
  become: false

- name: Check if sidebar needs to be added
  ansible.builtin.lineinfile:
    path: /{{ config_dir }}/home-assistant/config/configuration.yaml
    regex: "panel_iframe:"
    state: present
    register: sidebar_found

- name: Copy file to a temporary location
  ansible.builtin.copy:
    src: /{{ config_dir }}/home-assistant/config/configuration.yaml
    dest: /tmp/file.tmp
    mode: 0644
  when: sidebar_found.changed == false

- name: Add sidebar to configuration
  ansible.builtin.blockinfile:
    path: /tmp/file.tmp
    block: |
      panel_iframe:
        zigbee2mqtt:
          title: "zigbee2mqtt"
          url: "http://172.80.0.35:8080"
          icon: mdi:zigbee
          require_admin: true
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  when: sidebar_found.changed == false

- name: Update home assisant configuration file with sidebar
  ansible.builtin.copy:
    src: /tmp/file.tmp
    dest: /{{ config_dir }}/home-assistant/config/configuration.yaml
    mode: 0644
  when: sidebar_found.changed == false
