---
- name: Create mosquitto folders on Pi
  ansible.builtin.file:
    path: "{{ config_dir }}/mosquitto/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ''
    - 'data'
    - 'config'
    - 'log'
  become: false

- name: Copy mosquitto templates to Pi
  ansible.builtin.template:
    src: "templates/{{ item.src }}"
    dest: "/home/pi/mosquitto/{{ item.dest }}"
    mode: 0640
  loop:
    - src: 'eclipse-mosquitto-docker-compose.yml.j2'
      dest: 'docker-compose.yml'
    - src: 'eclipse-mosquitto-config'
      dest: 'config/mosquitto.conf'
  become: true

- name: Ensure mosquitto is running
  community.docker.docker_compose:
    project_src: "/home/pi/mosquitto/"
    build: false
  become: true

- name: Create and set password in mosquitto password file
  community.docker.docker_container_exec:
    container: "mosquitto"
    command: "{{ item }}"
  loop:
    - "touch /mosquitto/config/password.txt"
    - "mosquitto_passwd -b /mosquitto/config/password.txt {{ mosquitto_user }} {{ mosquitto_password }}"

- name: Enable authentication in mosquitto config
  replace:
    path: "/home/pi/mosquitto/config/mosquitto.conf"
    regexp: '#password_file /mosquitto/config/password.txt'
    replace: 'password_file /mosquitto/config/password.txt'

- name: Reload mosquitto configuration
  ansible.builtin.shell: kill -HUP $(pgrep -x mosquitto)
  args:
    warn: false
  ignore_errors: true
  become: true
