---
- name: Create WebRTC folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/webrtc"
    state: directory
    mode: 0755
  become: false

- name: Create config folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/webrtc/config"
    state: directory
    mode: 0755
  become: false

- name: Copy WebRTC docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/webrtc-docker-compose.yml.j2
    dest: "{{ config_dir }}/webrtc/docker-compose.yml"
    mode: 0640
  become: false

- name: Ensure WebRTC is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/webrtc/"
    build: false
  become: false