---
- name: Create zigbee2mqtt folders on Pi
  ansible.builtin.file:
    path: "{{ config_dir }}/zigbee2mqtt/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ''
    - 'data'
  become: false

- name: Copy zigbee2mqtt templates to Pi
  ansible.builtin.template:
    src: "templates/{{ item.src }}"
    dest: "{{ config_dir }}/zigbee2mqtt/{{ item.dest }}"
    mode: 0640
  loop:
    - src: 'zigbee2mqtt-config'
      dest: 'data/configuration.yaml'
    - src: 'zigbee2mqtt-docker-compose.yml.j2'
      dest: 'docker-compose.yml'
  become: false

- name: Ensure zigbee2mqtt is running
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/zigbee2mqtt/"
    build: false
  become: false