---
- name: Check if {{ var_sidebar.key }} is present in Home Assistant configuration
  ansible.builtin.lineinfile:
    path: /tmp/configuration.tmp
    line: "{{ var_sidebar.key }}:"
    state: present
  register: var_sidebar_present
  check_mode: true
  become: false
  when: var_sidebar.enabled | default(true)

- name: Add {{ var_sidebar.name }} to Home Assistant configuration
  ansible.builtin.blockinfile:
    path: /tmp/configuration.tmp
    insertafter: "{{ var_sidebar.key }}:"
    block: |2
      {% if var_sidebar.key == 'panel_iframe' %}
      {{ var_sidebar.key }}:
      {% else %}
        {{ var_sidebar.key }}:
      {% endif %}
      {% for key, value in var_sidebar.items() if key not in ['name', 'key', 'enabled'] %}
          {{ key }}: {{ value }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ var_sidebar.key }}"
  when: var_sidebar_present.changed and var_sidebar.enabled | default(true)
  become: false
